require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const Workout = require('./models/Workout');
const User = require('./models/User');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/fittrack';

async function main(){
  await mongoose.connect(MONGO_URI);
  console.log('Connected to Mongo for seeding');
  await Workout.deleteMany({});
  await User.deleteMany({});

  const workouts = [];
  const types = ['Cardio','Strength','HIIT','Stretching','Yoga','Cycling'];
  const equipment = ['None','Dumbbells','Barbell','Kettlebell','Treadmill','Bike'];
  for (let i=0;i<20;i++){
    const t = types[i % types.length];
    workouts.push({
      name: `${t} Session ${i+1}`,
      type: t,
      durationMinutes: 20 + (i%5)*10,
      caloriesBurned: 150 + i*10,
      intensity: ['Low','Medium','High'][i%3],
      date: new Date(Date.now() - i*24*60*60*1000),
      equipment: equipment[i % equipment.length],
      notes: `Autogenerated workout ${i+1}`
    });
  }

  await Workout.insertMany(workouts);
  const pw = await bcrypt.hash('password123', 10);
  await User.create({ username: 'admin', email: 'admin@example.com', passwordHash: pw });
  console.log('Seeded 20 workouts and admin user (username: admin, password: password123)');
  process.exit(0);
}

main().catch(err=>{console.error(err);process.exit(1)});
